### PR TITLE
Fixing #7

### LINKED ISSUE #7: #7
Expect another PR from me that fixes these:

- Remove useless if statements that check for `aiohttp` and `requests` installation. This is because both are installed with this module and the if statements are absolutely useless. Probably more useless than the second page of google search. Or more useless than a ropeless skipping rope, or a shoe umbrella or a noodle fan.

### PR DESCRIPTION
**Pull request by MarzaElise**
*moans* 
ah daddy, I fixes #7 please accepts me 
*moans again*
*seduces you* 
Please Daddy

### CODE REVIEW

**Comment by MarzaElise** [comment]
**PLEASE DADDY**

**Comment by MarzaElise** [comment]
*moans*

**Comment by MarzaElise** [comment]
Accept PR

**Comment by MarzaElise** [comment]
*seduces you more*

**Comment by Genoinno** [comment]
Ok now begone

**Comment by pgamerx** [comment]
I am scared to comment because I will start getting notifications for this

**Comment by MarzaElise** [comment]
_im sorry daddy_

**Pull request merged**
